# Generated by Django 4.0.2 on 2022-02-08 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('major_name', models.CharField(max_length=200)),
                ('school_email', models.EmailField(max_length=254)),
                ('birth_of_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('entrance_year', models.IntegerField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('nickname', models.CharField(max_length=200)),
                ('introducing', models.CharField(max_length=255, null=True)),
                ('school_auth_status', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('mbti_first', models.CharField(max_length=1, null=True)),
                ('mbti_second', models.CharField(max_length=1, null=True)),
                ('mbti_third', models.CharField(max_length=1, null=True)),
                ('mbti_fourth', models.CharField(max_length=1, null=True)),
                ('withdrawn_status', models.CharField(default='N', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
