# Generated by Django 4.0.2 on 2022-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_auth',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='010-1111-1111', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='college',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
