# Generated by Django 4.0.2 on 2022-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
