# Generated by Django 4.0.2 on 2022-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_auth_status',
            field=models.CharField(choices=[('Y', 'School authentication complete'), ('N', 'School authentication necessary')], default='N', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='withdrawn_status',
            field=models.CharField(choices=[('general', 'General Member'), ('withdrawal', 'Withdrawal member')], default='general', max_length=80),
        ),
    ]
