# Generated by Django 4.0.2 on 2022-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introducing',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_first',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_fourth',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_second',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_third',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
