# Generated by Django 4.0.2 on 2022-02-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_info',
        ),
        migrations.AlterField(
            model_name='major',
            name='college',
            field=models.ForeignKey(db_column='college', on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='users.college'),
        ),
        migrations.AlterField(
            model_name='major',
            name='university',
            field=models.ForeignKey(db_column='university', on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='users.college'),
        ),
    ]
