# Generated by Django 4.0.2 on 2022-02-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='university',
            field=models.ForeignKey(db_column='university', on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='users.university'),
        ),
    ]
