# Generated by Django 4.0.2 on 2022-02-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_college_name_alter_profile_major_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest_list',
            field=models.TextField(blank=True),
        ),
    ]
