# Generated by Django 4.0.2 on 2022-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_of_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entrance_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
