# Generated by Django 4.0.2 on 2022-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phone_auth_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_auth',
            field=models.IntegerField(null=True),
        ),
    ]
