# Generated by Django 4.0.2 on 2022-02-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_school_info_alter_major_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_name',
        ),
    ]
