# Generated by Django 4.0.2 on 2022-02-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_major_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.ForeignKey(db_column='university', on_delete=django.db.models.deletion.CASCADE, to='users.university'),
        ),
    ]
