# Generated by Django 4.0.2 on 2022-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
