# Generated by Django 4.0.2 on 2022-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_birth_of_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entrance_year',
            field=models.IntegerField(blank=True),
        ),
    ]
