# Generated by Django 4.0.2 on 2022-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_room_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='university',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
