# Generated by Django 4.0.2 on 2022-02-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_room_college'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('user', 'room')},
        ),
    ]
