# Generated by Django 4.0.2 on 2022-02-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_major_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('spot', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('meettime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.meet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meet_users',
                'unique_together': {('user', 'meet')},
            },
        ),
        migrations.AddField(
            model_name='meet',
            name='owner',
            field=models.ManyToManyField(through='users.MeetUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room'),
        ),
    ]
