# Generated by Django 4.0.2 on 2022-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_meet_meetuser_meet_owner_meet_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meettime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meet',
            name='spot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
