# Generated by Django 4.0.2 on 2022-05-22 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('grade_limit', models.IntegerField(blank=True, null=True)),
                ('heads_limit', models.IntegerField()),
                ('gender_limit', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not specified')], default='N', max_length=80)),
                ('meet_purpose', models.CharField(blank=True, max_length=255)),
                ('room_description', models.CharField(blank=True, max_length=255)),
                ('meet_status', models.CharField(choices=[('Y', 'Meeting exist'), ('N', 'Meeting not exist')], default='N', max_length=80)),
                ('room_open', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=80)),
                ('common', models.CharField(blank=True, max_length=80)),
                ('mbti', models.CharField(blank=True, max_length=255)),
                ('interest', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_users',
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ManyToManyField(through='rooms.RoomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
