# Generated by Django 4.0.2 on 2022-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agree',
            new_name='information_agree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_auth_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_status',
            field=models.CharField(choices=[('Registered', 'Registered - Should authenticate phone'), ('Phone complete', 'Phone complete -  Should enter profile'), ('Profile complete', 'Profile complete - Should authenticate school'), ('School complete', 'School complete - School authentication complete')], default='Registered', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='use_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entrance_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
