# Generated by Django 4.0.2 on 2022-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_birth_of_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agree',
            new_name='information_agree',
        ),
        migrations.AddField(
            model_name='user',
            name='use_agree',
            field=models.BooleanField(default=False),
        ),
    ]
