# Generated by Django 4.0.2 on 2022-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_school_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_status',
            field=models.CharField(choices=[('Registered', 'Registered - Should Enter Profile '), ('Profile complete', 'Profile complete - Should Authenticate School'), ('School complete', 'School complete - School Authentication Complete')], default='Registered', max_length=80),
        ),
    ]
