# Generated by Django 4.0.2 on 2022-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_status',
            field=models.CharField(choices=[('Registered', 'Registered - Should enter profile '), ('Profile complete', 'Profile complete - Should authenticate school'), ('School complete', 'School complete - School authentication complete')], default='Registered', max_length=80),
        ),
    ]
